package pl.lotto.numberreceiver;

public enum ValidateMessage {
    CORRECT_SIZE_NUMBERS,
    NOT_CORRECT_SIZE_NUMBERS,
    UNKNOWN_SIZE_NUMBERS,
    DUPLICATE_NUMBERS,
    DUPLICATE_NUMBERS_NOT_FOUND,
    IN_RANGE_NUMBERS,
    NOT_IN_RANGE_NUMBERS;
}
